# ============================================================
# Configuración de Plataforma de Inscripción de Cursos
# ============================================================

# Aplicación
spring.application.name=inscripcion-service
server.port=8080

# AWS
aws.region=us-east-1
aws.s3.bucket=cnative-semana4


# EFS (ruta de montaje dentro del contenedor Docker)
efs.mount.path=/app/efs

# Logs
logging.level.com.transportista=DEBUG
logging.level.software.amazon.awssdk=WARN




